create table registration(
    cook_id  int auto_increment primaery KEY,
    cooksName  varchar(50) not null,
    gender varchar(20) not null,
    Date_of_Birth DATE not null,
    fathers_name varchar(50) not null,
    email varchar(100) not null unique,
    phone_number varchar(15) not null,
    street_address varchar(50) not null,
    city varchar(30) not null,
    state varchar(30) not null,
    pincode varchar(20) not null,
    country varchar(50) not null,
    Aadhaar_number varchar(20) not null,
    pan_number varchar(20) not null,
    Account_holder_name varchar(50) not null,
    Bank_name varchar(50) not null,
    Account_number varchar(20) not null,
    IFSC_number varchar(30) not null,
    branch_name varchar(40) not null,
    Kitchen_name varchar(50) not null,
    About_me varchar(500) not null,
    experience varchar(20) not null,
    workingdays varchar(20) not null,
    created_on timestamp default current_timestamp
)